config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, :only => [:show]

  root 'welcome#index'
  get 'about' => 'welcome#about' 
  resources :tips, only: [:index]
  get '/search' => 'welcome#query'
  resources :courses, shallow: true do
   resources :holes do
     resources :tips do
      member do
        put "like" => "tips#upvote"
        put "dislike" => "tips#downvote"
      end
    end
  end
end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :holes
  has_many :tips, through: :holes
  validates :number_holes, presence: true
  validates :name, presence: true
  validates :state, presence: true
  validates :city, presence: true
  validates :style, presence: true
  validates_numericality_of :slope, :greater_than_or_equal_to => 55, :less_than_or_equal_to => 155 
  validates_numericality_of :rating  
end

app/models/hole.rb
class Hole < ActiveRecord::Base
  belongs_to :course
  has_many :tips
end

app/models/tip.rb
class Tip < ActiveRecord::Base
  before_save :capitalize_attributes
  belongs_to :user
  belongs_to :course
  belongs_to :hole
  validates :yardage, presence: true
  validates :body, presence: true
  validates :hole_id, :presence => true
  acts_as_votable

  def capitalize_attributes
    self.body = capitalize_sentences(body)
  end

  def capitalize_sentences(string)
    unless string.blank?
      string.gsub(/([a-z])((?:[^.?!]|\.(?=[a-z]))*)/i) { $1.upcase + $2.rstrip }
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_voter

  validates_format_of :first_name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
  validates_format_of :last_name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def welcome
  end
end

app/controllers/concerns/holes_helper.rb
module HolesHelper
  def create_holes(course)
    x = 0
    if course.number_holes == '9'
      9.times do
        hole = course.holes.create
        hole.hole_number = x += 1
        hole.save!
      end
    else
      18.times do
        hole = course.holes.create
        hole.hole_number = x += 1
        hole.save!
      end
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  include HolesHelper
  
  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      create_holes(@course)
      redirect_to course_path(@course)
    else
      render 'new'
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
      if @course.update(course_params)
        flash[:notice] = "Course successfully updated"
        redirect_to course_path(@course)
      else
        render :edit
      end
  end

  def show
    @course = Course.find(params[:id])
    @holes = @course.holes.order("id asc")
  end

  private

  def course_params
    params.require(:course).permit(
      :name,
      :state,
      :city,
      :architect,
      :style,
      :rating,
      :slope,
      :number_holes
    )
  end

end

app/controllers/holes_controller.rb
class HolesController < ApplicationController

  def edit
    @hole = Hole.find(params[:id])
    @course = Course.find(@hole.course_id)
  end

  def update
    @hole = Hole.find(params[:id])
    @course = Course.find(@hole.course_id)
      if @hole.update(hole_params)
        flash[:notice] = "Hole successfully updated"
        redirect_to course_path(@course)
      else
        render :edit
      end
  end

  private

  def hole_params
    params.require(:hole).permit(
      :yardage, :course_id, :par
    )
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_course_and_holes
  before_action :upvote_downvote_helper, only: [:upvote, :downvote]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    @tips = @hole.present? ? @hole.tips : Tip.all
  end

  def new
    @tip = @hole.tips.new
  end

  def create
    @tip = @hole.tips.new(tip_params)
    @tip.user = current_user
    if @tip.save
      redirect_to course_path(@course)
    else
      render 'new'
    end
  end

  def edit
    @tip = @hole.tips.find(params[:id])
  end

  def update
    @tip.update(tip_params)
    redirect_to course_path(@course)
  end

  def upvote
    @tip = Tip.find(params[:id])
    @tip.upvote_from current_user
    redirect_to course_path(@course)
  end

  def downvote
    @tip = Tip.find(params[:id])
    @tip.downvote_from current_user
    redirect_to course_path(@course)
  end

  def show
    @tip = Tip.find(params[:id])
  end


  private

  def tip_params
    params.require(:tip).permit(
      :body,:hole_id, :user_id, :yardage
      )
  end

  def set_course_and_holes
    @hole = Hole.find(params[:hole_id]) if params[:hole_id].present?
    @course = Course.find(@hole.course_id) if params[:hole_id].present?
  end
  
  def upvote_downvote_helper
    @tip = Tip.find(params[:id])
    @hole = Hole.find(@tip.hole_id)
    @course = Course.find(@hole.course_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate_user!

  def show
    @user = User.find_by(id: params[:id])
    @tips = Tip.where(user_id: @user.id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
 def index
 end

 def query
 end

 def results
 end

 def about
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/states_helper.rb
module StatesHelper
def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/views/courses/index.html.erb
<%= link_to "Add Course", new_course_path  %>

<% @courses.each do |course| %>
  <h3><%= link_to "#{course.name}", course_path(course)  %></h3>
<% end %>

app/views/courses/new.html.erb
<h2>Add Course</h2>
<%= form_for @course, :html => {:class => "form-horizontal"} do |form| %>
<div class="col-md-5">
  <div class='form-group'>
    <%= form.label :name, class:"control-label col-sm-2"%>
    <%= form.text_field :name, :class => 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :city, class:"control-label col-sm-2" %>
    <%= form.text_field :city, :class => 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :state, class:"control-label col-sm-2" %>
    <%= form.select :state, options_for_select(us_states), :class => 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :architect, class:"control-label col-sm-2" %>
    <%= form.text_field :architect, :class => 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :style, class:"control-label col-sm-2" %>
    <%= form.select :style, options_for_select([['Links', 'Links'], ['Parkland', 'Parkland'], ['Desert', 'Desert'], ['Heathland', 'Heathland'], ['Resort', 'Resort']]), :class => 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :rating,  class:"control-label col-sm-2" %>
    <%= form.text_field :rating, :class => 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :slope,  class:"control-label col-sm-2" %>
    <%= form.text_field :slope, :class => 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :number_holes, 'Holes',  class:"control-label col-sm-2" %>
    <%= form.select :number_holes, options_for_select([['9', '9'], ['18', '18']]), :class => 'dropdown-select' %>
  </div>

  <div class="col-sm-offset-2 col-sm-10">
    <%= form.submit 'submit', :id => 'form-button', :class => 'btn btn-default' %>
  </div>

</div>

<% end %>

app/views/courses/show.html.erb
<h1><%= @course.name %></h1>
  <% @holes.each do |hole| %>
    <h4>Hole <%= hole.hole_number %></h4>
      <% if hole.yardage && hole.par != nil %>
      <p><strong><%= hole.yardage %> yard Par <%= hole.par %></strong></p>
      <% end %>
        <% if hole.tips.length != 0 %>
          <% hole.tips.each do |tip| %>
           <div class="divider"></div>
             <div class="section">
               <div class='col s2 offset-s2'>
              <%= link_to like_tip_path(tip),  class: "upvote", method: :put do %>
                <i id="upvote" class="fa fa-caret-up fa-2x"></i>
              <% end %>
              <span class=''><%= tip.get_likes.size - tip.get_dislikes.size %></span>
              <span class='offset-s2'><%= tip.body %></span>
              <%= link_to dislike_tip_path(tip), class: "upvote", method: :put do %>
              <i id="upvote" class="fa fa-caret-down fa-2x"></i>
              </div>
          </div>
          <% end %>
       <% end %>
    <% end %>
    <%= link_to "Add a Tip", new_hole_tip_path(hole)  %>
  <% end %>

app/views/holes/edit.html.erb
<div class="container">
  <h1 class="page-header">Edit Hole <%= @hole.hole_number %></h1>

<%= form_for [@hole], method: :patch, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%=f.label :yardage, class: "control-label col-md-2" %>
    <div class="col-md-3">
      <%=f.text_field :yardage, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%=f.label :par, class: "control-label col-md-2" %>
    <div class="col-md-3">
      <%=f.select :par, options_for_select([['3', '3'], ['4', '4'], ['5', '5']]), :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
      <center><%= f.submit 'Update', id: "form-button", class:"btn" %></center>
        <%= link_to "Cancel", course_path(@course), class: "btn" %>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdcaddy</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'icon.ico' %>
  <%= csrf_meta_tags %>
</head>
<header class="group">
<div class="navbar-fixed">
<nav class="navbar nav-fullwidth navbar-pills" role="navigation">
  <nav>
    <div class="nav-wrapper">
    <div class="container">
      <a href="/" class="brand-logo">CrowdCaddy</a>
     <!--  <form method='get' id='search-form' action='/search' role="search">
      <label for="search"><i class="material-icons">search</i></label>
      <li><input type="text"/></li>
      </form> -->
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
      <% if current_user %>
        <li><%= link_to "#{current_user.first_name} ""#{current_user.last_name}", user_path(current_user) %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <% if current_user %>
        <li><%= link_to "#{current_user.first_name} ""#{current_user.last_name}", user_path(current_user) %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
      </ul>
    </div>
    </div>
  </nav>
    </header>
    <body>
    <main>
  <div class="container">
  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
  </div>
</body>
</main>
<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Connect</h5>
                <ul>
                  <li class='grey-text text-lighten-3'>Social Links and Email Sign Up Go Here</li>
                </ul>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="/about">About</a></li>
                  <li><a class="grey-text text-lighten-3" href="/courses">Find a Course</a></li>
                  <li><a class="grey-text text-lighten-3" href="mailto:bradystilwell@outlook.com?Subject=Hello!">Contact Us</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2015 CrowdCaddy
            </div>
          </div>
        </footer>

</html>

app/views/tips/index.html.erb
<% @tips.each do |tip| %>
   <p> <%= tip.body.gsub(/([a-z])((?:[^.?!]|\.(?=[a-z]))*)/i) { $1.upcase + $2.rstrip }%> 
    <% if tip.yardage != nil %>
      Yardage off tee: <%= tip.yardage %> </p>
   <% end %>
<% end %>

app/views/tips/new.html.erb
  <h2>Tip for Hole #<%= @hole.hole_number %> at <%= @course.name.titleize %></h2>
  <%= form_for [@hole, @tip], :class => 'form-horizontal' do |form| %>
    <div class='form-group'>
      <%= form.label :body, 'Tip', class:"control-label col-md-2" %>
      <%= form.text_area :body, :class => 'form-control' %>
    </div>
    
    <div class='form-group'>
      <%= form.label :yardage, 'Yardage', class:"control-label col-md-2" %>
      <%= form.text_field :yardage, :class => 'form-control' %>
    </div>

    <div class='form-group'>
      <%= form.submit 'submit', :id => 'form-button', :class => 'btn btn--full' %>
    </div>
  <% end %>

app/views/users/show.html.erb
<h5>This is where the profile page will go for <%= @user.first_name %></h3>
<% @tips.each do |tip| %>
  <p> <%= tip.hole.course.name %> </p>
  <p>Hole #<%= tip.hole.hole_number%>: <%= tip.body %> </p>
<% end %>

app/views/welcome/about.html.erb
<p>
  CrowdCaddy is a website that allows users to leave tips on holes of their choosing.
</p>

app/views/welcome/index.html.erb
<% if current_user %>
  <h1>Hello <%= current_user.first_name %>! </h1>
<% end %>

<%= link_to "Find a course", courses_path  %>